language: ruby
rvm:
  - 2.1.2
  - ruby-head
matrix:
  allow_failures:
    - rvm: ruby-head
bundler_args: "--without development:production --deployment"
cache: bundler

before_install:
  - gem install rubocop
  - gem install coveralls
  - gem install scss-lint

script:
  - bundle exec rubocop
  - bundle exec scss-lint app/assets/stylesheets/
