sudo: false
language: ruby
rvm:
  - 2.1.5
  - 2.2.1
  - ruby-head
matrix:
  allow_failures:
    - rvm: ruby-head
addons:
  postgresql: "9.4"
bundler_args: "--jobs=3 --retry=3 --without development:production --deployment"
cache: bundler

before_install:
  - gem update bundler

before_script:
  - psql -c 'create database coursemology_test;' -U postgres
  - bundle exec rake db:setup

script:
  - bundle exec consistency_fail
  - bundle exec rake spec

notifications:
  slack:
    secure: h++bTbn+z5gm8QAF+Fk9ExyCX+Oe++O++1jN/CrakTL7p19w0Cd8Xbt8VsNevaWWeu/CAd3mjTlkF4iE+VQCax0WO1Z1qJTCcj4fiVwJSF9ojRZoNTaQeZCaDsmce3XA1gUITvN+n/iu0aNQYi7XKsXBFwmkC/BkoA4e/euzft4=
