dist: trusty
sudo: true
language: ruby
branches:
  except:
    - /^bundle-update-[0-9]{4}-[0-9]{2}-[0-9]{2}-[0-9]{6}+$/
    - /^depfu\/update.*$/
rvm:
  - 2.4.2
services:
  - docker
addons:
  chrome: stable
  apt:
    packages:
      - ghostscript
  postgresql: "9.6"
  hosts:
    - coursemology.lvh.me
bundler_args: "--jobs=3 --retry=3 --without development:production --deployment"
cache:
  bundler: true
  yarn: true
  directories:
    - $HOME/.cache/yarn
    - $(npm root -g)
    - $(npm prefix -g)/bin
    - $TRAVIS_BUILD_DIR/client/hard-source-cache
env:
  global:
    - RAILS_ENV=test
  matrix:
    - GROUP="1,2"
    - GROUP="3,4"
    - GROUP="5,6"
    - GROUP="7,8"
    - GROUP="misc"

before_install:
  - nvm install 8
  - node --version
  - npm list -g yarn --depth=0 || npm install -g yarn
  - yarn --version
  - docker --version
  - cd client && yarn install --production && cd -

before_script:
  - psql -c 'create database coursemology_test;' -U postgres
  - psql -c 'create database coursemology_test2;' -U postgres
  - 'if [ -d "$TRAVIS_BUILD_DIR/client/hard-source-cache" ]; then ls -la $TRAVIS_BUILD_DIR/client/hard-source-cache; fi'
  - ls -la $TRAVIS_BUILD_DIR/client
  - cd client && yarn build:production && cd -
  - bundle exec rake parallel:setup[2]

script:
  - 'if [ "$GROUP" = "misc" ]; then bundle exec consistency_fail; fi'
  - 'if [ "$GROUP" = "misc" ]; then bundle exec i18n-tasks unused; fi'
  - 'if [ "$GROUP" = "misc" ]; then bundle exec i18n-tasks missing; fi'
  - 'if [ "$GROUP" = "misc" ]; then bundle exec rake factory_bot:lint; fi'
  - 'if [ "$GROUP" = "misc" ]; then bundle exec rake assets:precompile; fi'
  - 'if [ "$GROUP" = "misc" ]; then cd client && yarn; fi'
  - 'if [ "$GROUP" = "misc" ]; then yarn lint; fi'
  - 'if [ "$GROUP" = "misc" ]; then yarn test; fi'
  - 'if [ "$GROUP" = "misc" ]; then cd ..; fi'
  - 'if [ "$GROUP" != "misc" ]; then export CODECOV_FLAG=backend; fi'
  - 'if [ "$GROUP" != "misc" ]; then bundle exec parallel_rspec spec -n 8 --only-group $GROUP --runtime-log spec/fixtures/parallel_runtime_rspec.log; fi'
after_script:
  - 'if [ "$GROUP" = "misc" ]; then bash <(curl -s https://codecov.io/bash) -F frontend -s client/coverage; fi'

notifications:
  slack: coursemology:kdSjdF4xtXGOBIvMsbIF4gQ6
