sudo: false
language: ruby
branches:
  except:
    - /^bundle-update-[0-9]{4}-[0-9]{2}-[0-9]{2}-[0-9]{6}+$/
rvm:
  - 2.2.5
  - 2.3.1
  - ruby-head
matrix:
  allow_failures:
    - rvm: ruby-head
addons:
  postgresql: "9.4"
bundler_args: "--jobs=3 --retry=3 --without development:production --deployment"
cache: bundler

before_install:
  - gem update bundler
  # from https://github.com/travis-ci/travis-ci/issues/3225#issuecomment-177592725
  - mkdir travis-phantomjs
  - wget https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-2.1.1-linux-x86_64.tar.bz2 -O $PWD/travis-phantomjs/phantomjs-2.1.1-linux-x86_64.tar.bz2
  - tar -xvf $PWD/travis-phantomjs/phantomjs-2.1.1-linux-x86_64.tar.bz2 -C $PWD/travis-phantomjs
  - export PATH=$PWD/travis-phantomjs/phantomjs-2.1.1-linux-x86_64/bin:$PATH

before_script:
  - psql -c 'create database coursemology_test;' -U postgres
  - bundle exec rake db:setup

script:
  - bundle exec consistency_fail
  - bundle exec i18n-tasks health
  - bundle exec rake spec

notifications:
  slack:
    secure: h++bTbn+z5gm8QAF+Fk9ExyCX+Oe++O++1jN/CrakTL7p19w0Cd8Xbt8VsNevaWWeu/CAd3mjTlkF4iE+VQCax0WO1Z1qJTCcj4fiVwJSF9ojRZoNTaQeZCaDsmce3XA1gUITvN+n/iu0aNQYi7XKsXBFwmkC/BkoA4e/euzft4=
