sudo: false
language: ruby
branches:
  except:
    - /^bundle-update-[0-9]{4}-[0-9]{2}-[0-9]{2}-[0-9]{6}+$/
rvm:
  - 2.4.0
  - 2.3.1
matrix:
  allow_failures:
    - rvm: ruby-head
  exclude:
    - rvm: 2.2.5
      env: GROUP="checks"
addons:
  postgresql: "9.4"
  hosts:
    - coursemology.lvh.me
bundler_args: "--jobs=3 --retry=3 --without development:production --deployment"
cache:
  bundler: true
  directories:
    - travis-phantomjs
    - spec-runtime
before_cache:
  - mv $TRAVIS_BUILD_DIR/tmp/parallel_runtime_rspec.log $TRAVIS_BUILD_DIR/spec-runtime/parallel_runtime_rspec.log
env:
  global:
    - RAILS_ENV=test
    - COVERALLS_PARALLEL=true
  matrix:
    - GROUP="checks"
    - GROUP="test"

before_install:
  - nvm install node
  - node --version
  - gem update bundler
  # from https://github.com/travis-ci/travis-ci/issues/3225#issuecomment-177592725
  # and also from https://github.com/travis-ci/travis-ci/issues/3225#issuecomment-200965782
  - phantomjs --version
  - export PATH=$PWD/travis-phantomjs/phantomjs-2.1.1-linux-x86_64/bin:$PATH
  - phantomjs --version
  # Clear cache and download new copy of PhantomJS if the current version doesn't match 2.1.1.
  - "if [ $(phantomjs --version) != '2.1.1' ]; then rm -rf $PWD/travis-phantomjs; mkdir -p $PWD/travis-phantomjs; fi"
  - "if [ $(phantomjs --version) != '2.1.1' ]; then wget https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-2.1.1-linux-x86_64.tar.bz2 -O $PWD/travis-phantomjs/phantomjs-2.1.1-linux-x86_64.tar.bz2; fi"
  - "if [ $(phantomjs --version) != '2.1.1' ]; then tar -xvf $PWD/travis-phantomjs/phantomjs-2.1.1-linux-x86_64.tar.bz2 -C $PWD/travis-phantomjs; fi"
  - phantomjs --version
  - npm install --prefix ./client

before_script:
  - psql -c 'create database coursemology_test;' -U postgres
  - psql -c 'create database coursemology_test2;' -U postgres
  - 'if [ "$GROUP" = "test" ]; then npm run build:production --prefix ./client; fi'
#  - bundle exec rake db:setup
  - bundle exec rake parallel:setup[2]
  # Copy runtime log if it exists. Create runtime cache directory if absent.
  - 'if [ -f "$TRAVIS_BUILD_DIR/spec-runtime/parallel_runtime_rspec.log" ]; then cp $TRAVIS_BUILD_DIR/spec-runtime/parallel_runtime_rspec.log $TRAVIS_BUILD_DIR/tmp/parallel_runtime_rspec.log; cat $TRAVIS_BUILD_DIR/tmp/parallel_runtime_rspec.log; fi'
  - 'if [ ! -d "spec-runtime" ]; then mkdir spec-runtime; fi'

script:
  - 'if [ "$GROUP" = "checks" ]; then bundle exec consistency_fail; fi'
  - 'if [ "$GROUP" = "checks" ]; then bundle exec i18n-tasks health; fi'
  - 'if [ "$GROUP" = "checks" ]; then npm run build:production --prefix ./client; bundle exec rake assets:precompile; fi'
  - 'if [ "$GROUP" = "checks" ]; then npm run lint --prefix ./client; fi'
  - 'if [ "$GROUP" = "test" ]; then bundle exec rake parallel:spec[2]; fi'

after_script:
  - bundle exec codeclimate-test-reporter

notifications:
  webhooks:
    - https://coveralls.io/webhook?repo_token=klIDCAuOFrfbf5Eq6qt7P6lsBwXhc6vpQ
  slack: coursemology:kdSjdF4xtXGOBIvMsbIF4gQ6
